# Generated by Django 4.2.15 on 2024-09-16 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('optimal_water_level', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('efficiency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Maintenance')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PrecisionAgricultureMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_moisture', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rainfall', models.DecimalField(decimal_places=2, max_digits=5)),
                ('irrigation_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_management.crop')),
                ('irrigation_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_management.irrigationsystem')),
            ],
        ),
        migrations.AddField(
            model_name='irrigationsystem',
            name='water_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_management.watersource'),
        ),
    ]
