# Generated by Django 4.2.15 on 2024-09-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingUnit',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('town', models.CharField(max_length=100)),
                ('no', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
