# Generated by Django 4.2.15 on 2024-09-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0002_farmingunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmingunit',
            name='unit_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='farmingunit',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmingunit',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmingunit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='farmingunit',
            name='no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmingunit',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmingunit',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='farmingunit',
            table='water_management_farmingunit',
        ),
    ]
