# Generated by Django 4.2.15 on 2024-09-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0003_farmingunit_unit_id_alter_farmingunit_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FarmingUnit',
            new_name='Farming',
        ),
        migrations.AlterModelTable(
            name='farming',
            table='water_management_farming',
        ),
    ]
