# Generated by Django 4.2.15 on 2024-09-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0004_rename_farmingunit_farming_alter_farming_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='farming',
            table='water_management_farmingunit',
        ),
    ]
