# Generated by Django 4.2.15 on 2024-09-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0005_alter_farming_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farming',
            old_name='unit_id',
            new_name='reqno',
        ),
        migrations.AlterField(
            model_name='farming',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
