# Generated by Django 4.2.15 on 2024-09-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0006_rename_unit_id_farming_reqno_alter_farming_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='farming',
            table='water_management_farmingunitnew',
        ),
    ]
