# Generated by Django 4.2.15 on 2024-09-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0008_alter_farming_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farming',
        ),
    ]
