# Generated by Django 4.2.15 on 2024-09-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0010_farmingunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmingunit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
