# Generated by Django 4.2.15 on 2024-09-17 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0011_alter_farmingunit_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farmingunit',
        ),
    ]
