# Generated by Django 4.2.15 on 2024-09-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0012_delete_farmingunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmingunit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reqno', models.CharField(blank=True, max_length=20, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('no', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'water_management_farmingunit',
            },
        ),
    ]
