# Generated by Django 4.2.15 on 2024-09-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0013_farmingunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmingunit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
