# Generated by Django 4.2.15 on 2024-09-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0014_alter_farmingunit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmingunit',
            name='reqno',
        ),
        migrations.AddField(
            model_name='farmingunit',
            name='UNKNOWN_REQNO',
            field=models.CharField(default='UNKNOWN_REQNO', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='farmingunit',
            name='amount',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='farmingunit',
            name='district',
            field=models.CharField(default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmingunit',
            name='no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farmingunit',
            name='town',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farmingunit',
            name='type',
            field=models.CharField(default='Farming units/enterprise', max_length=100),
        ),
        migrations.AlterModelTable(
            name='farmingunit',
            table=None,
        ),
    ]
