# Generated by Django 4.2.15 on 2024-09-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0015_remove_farmingunit_reqno_farmingunit_unknown_reqno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmingunit',
            old_name='UNKNOWN_REQNO',
            new_name='reqno',
        ),
        migrations.AlterField(
            model_name='farmingunit',
            name='district',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmingunit',
            name='town',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
