# Generated by Django 4.2.15 on 2024-09-18 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0018_farmingunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardeningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('plant_countdown_days', models.IntegerField()),
                ('last_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('100', '100'), ('50', '50'), ('0', '0')], max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='farmingunit',
            old_name='reqno',
            new_name='req',
        ),
    ]
