# Generated by Django 4.2.15 on 2024-09-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0019_gardeningschedule_rename_reqno_farmingunit_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardeningschedule',
            name='default_days',
            field=models.IntegerField(default=0),
        ),
    ]
