# Generated by Django 4.2.15 on 2024-09-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0020_gardeningschedule_default_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardeningschedule',
            name='gnumber',
            field=models.IntegerField(default=2),
        ),
    ]
