# Generated by Django 4.2.15 on 2024-09-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0022_remove_gardeningschedule_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardeningschedule',
            name='plant_countdown_days',
            field=models.IntegerField(default=7),
        ),
    ]
